process_variants:
  raw_data_path: https://huggingface.co/datasets/plantcad/maize-allele-frequency-raw-data/resolve/main/Maize_Hapmap3_Exclude_TE_PlantCAD_Zero_Shot_Scores.parquet

ensembl_vep_annotation:
  cache_url: https://ftp.ebi.ac.uk/ensemblgenomes/pub/plants/release-62/variation/indexed_vep_cache/zea_mays_vep_62_Zm-B73-REFERENCE-NAM-5.0.tar.gz
  cache_version: 62
  species: zea_mays
  docker_image: ensemblorg/ensembl-vep:release_115.1

group_consequences:
  groups:
    grouped_splice:
      - splice_polypyrimidine_tract_variant
      - splice_region_variant
      - splice_donor_region_variant
      - splice_donor_variant
      - splice_donor_5th_base_variant
      - splice_acceptor_variant
    grouped_start_stop:
      - stop_gained
      - stop_lost
      - start_lost
  include:
    - intergenic_variant
    - intron_variant
    - upstream_gene_variant
    - downstream_gene_variant
    - 3_prime_UTR_variant
    - synonymous_variant
    - missense_variant
    - 5_prime_UTR_variant
    - grouped_splice
    - non_coding_transcript_exon_variant
    - grouped_start_stop

add_genome_repeats:
  genome_url: https://ftp.ensemblgenomes.ebi.ac.uk/pub/plants/release-62/fasta/zea_mays/dna/Zea_mays.Zm-B73-REFERENCE-NAM-5.0.dna_sm.toplevel.fa.gz

create_and_publish_dataset:
  split_chroms:
    validation: ["1", "3", "5", "7", "9"]
    test: ["2", "4", "6", "8", "10"]
  max_n:
    "10k": 10000
    "20k": 20000
  include:
    - intergenic_variant
    - intron_variant
    - upstream_gene_variant
    - downstream_gene_variant
    - 3_prime_UTR_variant
    - synonymous_variant
    - missense_variant
    - 5_prime_UTR_variant
    - grouped_splice
    - non_coding_transcript_exon_variant
    - grouped_start_stop
  groups:
    grouped_splice:
      - splice_polypyrimidine_tract_variant
      - splice_region_variant
      - splice_donor_region_variant
      - splice_donor_variant
      - splice_donor_5th_base_variant
      - splice_acceptor_variant
    grouped_start_stop:
      - stop_gained
      - stop_lost
      - start_lost
  default_config: "10k_all_consequences"
  output_hf_path: plantcad/maize-allele-frequency-test
  seed: 42

executor:
  prefix: /tmp/maize_dataset_test
